name: array_and_slice
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: checkout main
        uses: actions/checkout@main
      - name: run make test
        run: make -C array_and_slice test
