name: integers
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: checkout to main
        uses: actions/checkout@main
      - name: runs make test
        run: make -C integers test
